DROP SCHEMA IF EXISTS zazzacrifice;
CREATE SCHEMA zazzacrifice;
USE zazzacrifice;


CREATE TABLE users (
user_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT UNIQUE,
username VARCHAR(30) NOT NULL UNIQUE,
password VARCHAR(30) NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE game_sessions (
game_session_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT UNIQUE,
user INT UNSIGNED NOT NULL,
time_on_seconds INT UNSIGNED NOT NULL,
number_of_battles INT UNSIGNED NOT NULL,
number_of_damaged_made INT UNSIGNED NOT NULL,
elements_obtained INT UNSIGNED NOT NULL,
finished BIT NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (user) REFERENCES users(user_id) ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE events (
event_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT UNIQUE,
name VARCHAR(40) NOT NULL UNIQUE
)ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

CREATE TABLE game_events (
game_events_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT UNIQUE,
event INT UNSIGNED NOT NULL ,
game INT UNSIGNED NOT NULL REFERENCES game_sessions(game_id),
is_active BIT NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (event) REFERENCES events(event_id) ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE stats (
stat_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT UNIQUE,
name VARCHAR(5) NOT NULL UNIQUE
)ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

CREATE TABLE classes (
class_id TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT UNIQUE,
name VARCHAR(20) NOT NULL UNIQUE
)ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

CREATE TABLE consumable (
consumable_id SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT UNIQUE,
name VARCHAR(40) NOT NULL UNIQUE,
description VARCHAR(255) NOT NULL,
stat INT UNSIGNED NOT NULL ,
value INT UNSIGNED NOT NULL,
time_in_second SMALLINT UNSIGNED NOT NULL,
FOREIGN KEY (stat) REFERENCES stats(stat_id) ON UPDATE CASCADE
)ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

CREATE TABLE weapons (
weapon_id TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT UNIQUE,
name VARCHAR(40) NOT NULL UNIQUE,
description VARCHAR(255) NOT NULL,
stat INT UNSIGNED NOT NULL ,
value INT UNSIGNED NOT NULL,
class TINYINT UNSIGNED NOT NULL ,
FOREIGN KEY (stat) REFERENCES stats(stat_id) ON UPDATE CASCADE,
FOREIGN KEY (class) REFERENCES classes(class_id) ON UPDATE CASCADE
)ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

CREATE TABLE scenes (
scene_id TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT UNIQUE,
name VARCHAR(30)
)ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

CREATE TABLE checkpoints (
checkpoint_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT UNIQUE,
scene TINYINT UNSIGNED NOT NULL,
x_postion INT UNSIGNED NOT NULL,
y_position INT UNSIGNED NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (scene) REFERENCES scenes(scene_id) ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE players (
player_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT UNIQUE NOT NULL,
game_session INT UNSIGNED NOT NULL ,
name VARCHAR(15) NOT NULL,
money INT UNSIGNED NOT NULL,
checkpoint INT UNSIGNED,
class TINYINT UNSIGNED NOT NULL ,
FOREIGN KEY (game_session) REFERENCES game_sessions(game_session_id) ON UPDATE CASCADE,
FOREIGN KEY (checkpoint) REFERENCES checkpoints(checkpoint_id) ON UPDATE CASCADE,
FOREIGN KEY (class) REFERENCES classes(class_id) ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE consumables_players (
consumable_player_id SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT UNIQUE,
player INT UNSIGNED NOT NULL ,
consumable SMALLINT UNSIGNED NOT NULL,
amount TINYINT UNSIGNED NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (player) REFERENCES players(player_id) ON UPDATE CASCADE,
FOREIGN KEY (consumable) REFERENCES consumable(consumable_id) ON UPDATE CASCADE

)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE weapons_players (
weapon_player_id SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT UNIQUE,
weapon TINYINT UNSIGNED,
player INT UNSIGNED NOT NULL,
equipped BIT NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (weapon) REFERENCES weapons(weapon_id) ON UPDATE CASCADE,
FOREIGN KEY (player) REFERENCES players(player_id) ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE stats_players (
stat_player_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT UNIQUE,
player INT UNSIGNED NOT NULL,
stat INT UNSIGNED  NOT NULL ,
value TINYINT UNSIGNED NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (player) REFERENCES players(player_id) ON UPDATE CASCADE,
FOREIGN KEY (stat) REFERENCES stats(stat_id) ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE elements (
element_id tinyint unsigned PRIMARY KEY AUTO_INCREMENT UNIQUE,
name varchar(30) NOT NULL UNIQUE,
weakness tinyint unsigned,
FOREIGN KEY (weakness) REFERENCES elements(element_id) 
)ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

CREATE TABLE elements_players (
element_player_id int unsigned PRIMARY KEY AUTO_INCREMENT UNIQUE,
element tinyint unsigned not null,
player int unsigned not null,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (element) REFERENCES elements(element_id)ON UPDATE CASCADE,
FOREIGN KEY (player) REFERENCES players(player_id) ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE attacks (
attack_id int unsigned PRIMARY KEY AUTO_INCREMENT UNIQUE,
name varchar(30) UNIQUE,
description varchar(150),
value int unsigned
)ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

CREATE TABLE players_attacks (
player_attack_id int unsigned PRIMARY KEY AUTO_INCREMENT UNIQUE,
player int unsigned not null,
attack int unsigned not null,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (attack) REFERENCES attacks(attack_id)ON UPDATE CASCADE,
FOREIGN KEY (player) REFERENCES players(player_id) ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;